name: FastAPI CI/CD (Python 3.12)

on:
  push:
    branches: [ "master" ]

jobs:
  test-and-verify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt        

    - name: Run tests
      run: |
        pytest tests/  -v

    - name: Start server and verify reachability
      run: |
        uvicorn app.main:app --host 0.0.0.0 --port 8000 &  # Updated path
        sleep 10
        curl -sSf http://localhost:8000/health || exit 1